clear all;
close all;
clc;
a=imread('CAR.jpg');
a=rgb2gray(a);
b=edge(a,"roberts");
c=edge(a,"sobel");
d=edge(a,"prewitt");
e=edge(a,"log");
f=edge(a,"canny");
imshow(a);
title('Original image');
figure;
imshow(b);
title('Robert image');
figure;
imshow(c);
title('sobel image');
figure;
imshow(d);
title('prewitt image');
figure;
imshow(e);
title('log image');
figure;
imshow(f);
title('canny image');
